### ISSUE TITLE
Attribute error for update_selected_column9_values.py

### ISSUE THREAD

**Issue by gjaqu054** [jorvis/biocode#57]
Hi, 
I am trying to add "EC-numbers" to a gff file. 
This is my command:

 python update_selected_column9_values.py -i LMA_1258_IMG.gff3 -u ID_EC_onlycol1258.tab -k 'ID' -a 'ec_num' -o LMA_1258_IMG_EC.gff

And this is the error I am getting: 

Traceback (most recent call last):
  File "update_selected_column9_values.py", line 100, in <module>
    main()
  File "update_selected_column9_values.py", line 90, in main
    atts = gff.column_9_dict(cols[8])
AttributeError: module 'biocode.gff' has no attribute 'column_9_dict'

What am I doing wrong ? 

Thank you

**Comment by jorvis** [comment]
All of biocode uses Python3 rather than Python2.  In the example you gave, instead of running the script directly (which would have invoked python3 due to the shebang line) you typed **python** followed by the script name, which invokes python2.  Instead, run the script directly like this:

./update_selected_column9_values.py -i LMA_1258_IMG.gff3 -u ID_EC_onlycol1258.tab -k 'ID' -a 'ec_num' -o LMA_1258_IMG_EC.gff

Let me know if that doesn't fix the issue.
