### ISSUE TITLE
[convert_genbank_to_gff3.py] No Locus_tag present in my genbank file 

### ISSUE THREAD

**Issue by j-bacal** [jorvis/biocode#76]
Hi there,
 I'm trying to convert the[ following file to GFF3 ](https://www.ncbi.nlm.nih.gov/nuccore/GQ994935.1?report=genbank&to=138146) for a friend.
The file doesn't have any "locus_tag" attached to it.

I'm getting the following error :

`UnboundLocalError: local variable 'locus_tag' referenced before assignment
`

Is there a way to modify the script so that the script could work ?

Thank you
Julien

**Comment by jorvis** [comment]
Looking at this now, but did you also see that where you downloaded this from NCBI they now offer GFF3 file downloads directly?

![bug](https://user-images.githubusercontent.com/330899/157545288-b5290cbf-c564-44b0-80d2-d71782b71d3a.png)

**Comment by jorvis** [comment]
For files like this which have only CDS features and no other elements of the feature graph I don't think this script is going to support them, especially if it's so easy just to download from NCBI.  There aren't any identifiers at all for the individual CDS elements.  For typical feature table elements they are linked to a gene via their /locus_id elements, which is why the script here failed when searching for one.
